// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/grocer.proto

package out_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"fixed64,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,4,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_grocer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    uint64                 `protobuf:"fixed64,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *uint64                `protobuf:"fixed64,3,opt,name=parentId,proto3,oneof" json:"parentId,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_grocer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Category) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    uint64                 `protobuf:"fixed64,1,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_proto_grocer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{2}
}

func (x *Merchant) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"fixed64,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    uint64                 `protobuf:"fixed64,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	MerchantId    uint64                 `protobuf:"fixed64,4,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	Normalized    string                 `protobuf:"bytes,5,opt,name=normalized,proto3" json:"normalized,omitempty"`
	Aliases       []string               `protobuf:"bytes,6,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_grocer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Item) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Item) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *Item) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     uint64                 `protobuf:"fixed64,1,opt,name=receiptId,proto3" json:"receiptId,omitempty"`
	MerchantId    uint64                 `protobuf:"fixed64,2,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	OwnerId       uint64                 `protobuf:"fixed64,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Date          uint64                 `protobuf:"fixed64,4,opt,name=date,proto3" json:"date,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,5,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	Items         []*ReceiptItem         `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Total         float32                `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_grocer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{4}
}

func (x *Receipt) GetReceiptId() uint64 {
	if x != nil {
		return x.ReceiptId
	}
	return 0
}

func (x *Receipt) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Receipt) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Receipt) GetDate() uint64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Receipt) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Receipt) GetItems() []*ReceiptItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Receipt) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReceiptItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"fixed64,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float32                `protobuf:"fixed32,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptItem) Reset() {
	*x = ReceiptItem{}
	mi := &file_proto_grocer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptItem) ProtoMessage() {}

func (x *ReceiptItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptItem.ProtoReflect.Descriptor instead.
func (*ReceiptItem) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiptItem) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ReceiptItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReceiptItem) GetUnitPrice() float32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    uint64                 `protobuf:"fixed64,1,opt,name=proposalId,proto3" json:"proposalId,omitempty"`
	OwnerId       uint64                 `protobuf:"fixed64,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Merchant      string                 `protobuf:"bytes,3,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Date          uint64                 `protobuf:"fixed64,4,opt,name=date,proto3" json:"date,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,5,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	Items         []*ProposalItem        `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Total         float32                `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_proto_grocer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{6}
}

func (x *Proposal) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *Proposal) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Proposal) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *Proposal) GetDate() uint64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Proposal) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Proposal) GetItems() []*ProposalItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Proposal) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Proposal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProposalItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParsedName    string                 `protobuf:"bytes,1,opt,name=parsedName,proto3" json:"parsedName,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float32                `protobuf:"fixed32,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	MatchedItemId uint64                 `protobuf:"fixed64,4,opt,name=matchedItemId,proto3" json:"matchedItemId,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CategoryId    uint64                 `protobuf:"fixed64,6,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	IsNewCategory bool                   `protobuf:"varint,7,opt,name=isNewCategory,proto3" json:"isNewCategory,omitempty"`
	UserChoice    string                 `protobuf:"bytes,8,opt,name=userChoice,proto3" json:"userChoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalItem) Reset() {
	*x = ProposalItem{}
	mi := &file_proto_grocer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalItem) ProtoMessage() {}

func (x *ProposalItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalItem.ProtoReflect.Descriptor instead.
func (*ProposalItem) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{7}
}

func (x *ProposalItem) GetParsedName() string {
	if x != nil {
		return x.ParsedName
	}
	return ""
}

func (x *ProposalItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProposalItem) GetUnitPrice() float32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *ProposalItem) GetMatchedItemId() uint64 {
	if x != nil {
		return x.MatchedItemId
	}
	return 0
}

func (x *ProposalItem) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ProposalItem) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProposalItem) GetIsNewCategory() bool {
	if x != nil {
		return x.IsNewCategory
	}
	return false
}

func (x *ProposalItem) GetUserChoice() string {
	if x != nil {
		return x.UserChoice
	}
	return ""
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Merchants     []*Merchant            `protobuf:"bytes,3,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Items         []*Item                `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Receipts      []*Receipt             `protobuf:"bytes,5,rep,name=receipts,proto3" json:"receipts,omitempty"`
	Proposals     []*Proposal            `protobuf:"bytes,6,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_grocer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{8}
}

func (x *Snapshot) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Snapshot) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Snapshot) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *Snapshot) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Snapshot) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *Snapshot) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type BotUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=externalId,proto3" json:"externalId,omitempty"`
	UserId        uint64                 `protobuf:"fixed64,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotUser) Reset() {
	*x = BotUser{}
	mi := &file_proto_grocer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotUser) ProtoMessage() {}

func (x *BotUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grocer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotUser.ProtoReflect.Descriptor instead.
func (*BotUser) Descriptor() ([]byte, []int) {
	return file_proto_grocer_proto_rawDescGZIP(), []int{9}
}

func (x *BotUser) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *BotUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_grocer_proto protoreflect.FileDescriptor

const file_proto_grocer_proto_rawDesc = "" +
	"\n" +
	"\x12proto/grocer.proto\x12\x06grocer\"r\n" +
	"\x04User\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x06R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\"\n" +
	"\fpasswordHash\x18\x04 \x01(\tR\fpasswordHash\"\x8a\x01\n" +
	"\bCategory\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x06R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\bparentId\x18\x03 \x01(\x06H\x00R\bparentId\x88\x01\x01\x12\x1c\n" +
	"\tsortOrder\x18\x04 \x01(\x05R\tsortOrderB\v\n" +
	"\t_parentId\">\n" +
	"\bMerchant\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x01 \x01(\x06R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xac\x01\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x06R\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x06R\n" +
	"categoryId\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x04 \x01(\x06R\n" +
	"merchantId\x12\x1e\n" +
	"\n" +
	"normalized\x18\x05 \x01(\tR\n" +
	"normalized\x12\x18\n" +
	"\aaliases\x18\x06 \x03(\tR\aaliases\"\xd2\x01\n" +
	"\aReceipt\x12\x1c\n" +
	"\treceiptId\x18\x01 \x01(\x06R\treceiptId\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x02 \x01(\x06R\n" +
	"merchantId\x12\x18\n" +
	"\aownerId\x18\x03 \x01(\x06R\aownerId\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x06R\x04date\x12\x1a\n" +
	"\bphotoUrl\x18\x05 \x01(\tR\bphotoUrl\x12)\n" +
	"\x05items\x18\x06 \x03(\v2\x13.grocer.ReceiptItemR\x05items\x12\x14\n" +
	"\x05total\x18\a \x01(\x02R\x05total\"_\n" +
	"\vReceiptItem\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x06R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x03 \x01(\x02R\tunitPrice\"\xea\x01\n" +
	"\bProposal\x12\x1e\n" +
	"\n" +
	"proposalId\x18\x01 \x01(\x06R\n" +
	"proposalId\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\x06R\aownerId\x12\x1a\n" +
	"\bmerchant\x18\x03 \x01(\tR\bmerchant\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x06R\x04date\x12\x1a\n" +
	"\bphotoUrl\x18\x05 \x01(\tR\bphotoUrl\x12*\n" +
	"\x05items\x18\x06 \x03(\v2\x14.grocer.ProposalItemR\x05items\x12\x14\n" +
	"\x05total\x18\a \x01(\x02R\x05total\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x94\x02\n" +
	"\fProposalItem\x12\x1e\n" +
	"\n" +
	"parsedName\x18\x01 \x01(\tR\n" +
	"parsedName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x03 \x01(\x02R\tunitPrice\x12$\n" +
	"\rmatchedItemId\x18\x04 \x01(\x06R\rmatchedItemId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x06 \x01(\x06R\n" +
	"categoryId\x12$\n" +
	"\risNewCategory\x18\a \x01(\bR\risNewCategory\x12\x1e\n" +
	"\n" +
	"userChoice\x18\b \x01(\tR\n" +
	"userChoice\"\x91\x02\n" +
	"\bSnapshot\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.grocer.UserR\x05users\x120\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x10.grocer.CategoryR\n" +
	"categories\x12.\n" +
	"\tmerchants\x18\x03 \x03(\v2\x10.grocer.MerchantR\tmerchants\x12\"\n" +
	"\x05items\x18\x04 \x03(\v2\f.grocer.ItemR\x05items\x12+\n" +
	"\breceipts\x18\x05 \x03(\v2\x0f.grocer.ReceiptR\breceipts\x12.\n" +
	"\tproposals\x18\x06 \x03(\v2\x10.grocer.ProposalR\tproposals\"A\n" +
	"\aBotUser\x12\x1e\n" +
	"\n" +
	"externalId\x18\x01 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x06R\x06userIdB\rZ\v./out_protob\x06proto3"

var (
	file_proto_grocer_proto_rawDescOnce sync.Once
	file_proto_grocer_proto_rawDescData []byte
)

func file_proto_grocer_proto_rawDescGZIP() []byte {
	file_proto_grocer_proto_rawDescOnce.Do(func() {
		file_proto_grocer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grocer_proto_rawDesc), len(file_proto_grocer_proto_rawDesc)))
	})
	return file_proto_grocer_proto_rawDescData
}

var file_proto_grocer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_grocer_proto_goTypes = []any{
	(*User)(nil),         // 0: grocer.User
	(*Category)(nil),     // 1: grocer.Category
	(*Merchant)(nil),     // 2: grocer.Merchant
	(*Item)(nil),         // 3: grocer.Item
	(*Receipt)(nil),      // 4: grocer.Receipt
	(*ReceiptItem)(nil),  // 5: grocer.ReceiptItem
	(*Proposal)(nil),     // 6: grocer.Proposal
	(*ProposalItem)(nil), // 7: grocer.ProposalItem
	(*Snapshot)(nil),     // 8: grocer.Snapshot
	(*BotUser)(nil),      // 9: grocer.BotUser
}
var file_proto_grocer_proto_depIdxs = []int32{
	5, // 0: grocer.Receipt.items:type_name -> grocer.ReceiptItem
	7, // 1: grocer.Proposal.items:type_name -> grocer.ProposalItem
	0, // 2: grocer.Snapshot.users:type_name -> grocer.User
	1, // 3: grocer.Snapshot.categories:type_name -> grocer.Category
	2, // 4: grocer.Snapshot.merchants:type_name -> grocer.Merchant
	3, // 5: grocer.Snapshot.items:type_name -> grocer.Item
	4, // 6: grocer.Snapshot.receipts:type_name -> grocer.Receipt
	6, // 7: grocer.Snapshot.proposals:type_name -> grocer.Proposal
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_grocer_proto_init() }
func file_proto_grocer_proto_init() {
	if File_proto_grocer_proto != nil {
		return
	}
	file_proto_grocer_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grocer_proto_rawDesc), len(file_proto_grocer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_grocer_proto_goTypes,
		DependencyIndexes: file_proto_grocer_proto_depIdxs,
		MessageInfos:      file_proto_grocer_proto_msgTypes,
	}.Build()
	File_proto_grocer_proto = out.File
	file_proto_grocer_proto_goTypes = nil
	file_proto_grocer_proto_depIdxs = nil
}
